<?php

return [
    'OK_STATUS'=>200,
    'CREATED_STATUS'=>201,
    'UPDATED_STATUS'=>204,
    'NOT_FOUND_STATUS' => 404,
    'WRONG_VALIDATION_STATUS' => 422,
    'UNAUTHORIZED_VALIDATION_STATUS' => 401,
    'PAGINATION_NUMBER'=>10,
    'PAGINATION_NUMBER_DASHBOARD'=>10,
    'CANCELED_DAYS_PERIOD'=>28,
    'WARNING_DAYS_PERIOD'=>26,
    'LANGS'=>['en','ar']
]

?>