<?php

return [
    'OK_STATUS'=>200,
    'CREATED_STATUS'=>201,
    'UPDATED_STATUS'=>204,
    'NOT_FOUND_STATUS' => 404,
    'WRONG_VALIDATION_STATUS' => 422,
    'UNAUTHORIZED_VALIDATION_STATUS' => 401,
    'PAGINATION_NUMBER'=>10,
    'PAGINATION_NUMBER_DASHBOARD'=>10,
    'CAMPAIGN_FIRST_PAYMENT_PERIOD' => 28,
    'CAMPAIGN_FIRST_PAYMENT_REMINDER' => 23,
    'CAMPAIGN_FULL_PAYMENT_REMINDER' => 3,
    'CAMPAIGN_FULL_PAYMENT_PERIOD' => 10,
    'CAMPAIGN_INFLUENCER_CONTRACT_CANCELLED' => 3,
    'WARNING_DAYS_PERIOD'=>26,
    'CANCELED_DAYS_PERIOD'=>28,
    'RESET_DAYS_PERIOD'=>30,
    'LANGS'=>['en','ar'],
    'CUSTOMER_ADS_STATUS'=>['Active','WaitingPayment','Pending','Finished','Rejected'],
    'INFLUENCER_ADS_STATUS'=>['Pending','Active','Completed','Rejected'],
    'SOCKET_URL' => 'ws://127.0.0.1:3000',
    'PAYMENT_USERNAME'=>'almuu',
    'PAYMENT_PASSWORD'=>'almuu@123',
    'PAYMENT_KEY'=>'5cb5d43decb30818e4223a573f8708af6b7fefce1f1e3e88109027729a383839',
    'TAX'=> 15,

]

?>
